[build]
jobs = 16

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-Clink-arg=-fuse-ld=mold"]

[net]
git-fetch-with-cli = true

[registries.crates-io]
protocol = "sparse"

[alias]
b = "build"
br = "build --release"
bp = "build --profile production"
